import type { Video, Model, NavGroup, PageTitles } from "@cineai/domain-types";

export const VIDEOS: Video[] = [
  {
    id: 1,
    name: "Cyberpunk City Rain",
    model: "Kling 2.6",
    modelCls: "vm-k",
    time: "2h ago",
    dur: "00:08",
    status: "done",
    scene: "cyberpunk",
  },
  {
    id: 2,
    name: "Ocean Sunrise 4K",
    model: "Veo 3.1",
    modelCls: "vm-v",
    time: "3h ago",
    dur: "00:05",
    status: "proc",
    scene: "ocean",
  },
  {
    id: 3,
    name: "Forest Walk Drone",
    model: "Sora 2 Pro",
    modelCls: "vm-s",
    time: "Yesterday",
    dur: "00:15",
    status: "done",
    scene: "forest",
  },
  {
    id: 4,
    name: "Galaxy Flythrough",
    model: "Luma Ray3",
    modelCls: "vm-l",
    time: "2 days",
    dur: "00:10",
    status: "done",
    scene: "galaxy",
  },
  {
    id: 5,
    name: "Volcano Eruption",
    model: "Runway Gen-4.5",
    modelCls: "vm-r",
    time: "2 days",
    dur: "00:08",
    status: "done",
    scene: "volcano",
  },
  {
    id: 6,
    name: "Arctic Aurora",
    model: "Kling 2.6",
    modelCls: "vm-k",
    time: "3 days",
    dur: "00:12",
    status: "done",
    scene: "arctic",
  },
  {
    id: 7,
    name: "Desert Sandstorm",
    model: "Veo 3.1",
    modelCls: "vm-v",
    time: "4 days",
    dur: "00:07",
    status: "done",
    scene: "desert",
  },
  {
    id: 8,
    name: "Waterfall Mist",
    model: "Luma Ray3",
    modelCls: "vm-l",
    time: "5 days",
    dur: "00:09",
    status: "done",
    scene: "waterfall",
  },
];

export const MODELS: Model[] = [
  {
    name: "Kling 2.6",
    by: "Kuaishou",
    color: "#3EE8FF",
    tags: ["Best Motion", "4K", "2min"],
    quality: 96,
    speed: 78,
    realism: 92,
    res: "4K · 2min",
    badge: "TOP",
  },
  {
    name: "Veo 3.1",
    by: "Google DeepMind",
    color: "#4285F4",
    tags: ["Native Audio", "4K", "20s"],
    quality: 94,
    speed: 82,
    realism: 90,
    res: "4K · 20s",
    badge: "NEW",
  },
  {
    name: "Sora 2 Pro",
    by: "OpenAI",
    color: "#10A37F",
    tags: ["Physics AI", "60s"],
    quality: 91,
    speed: 65,
    realism: 95,
    res: "1080p · 60s",
    badge: "",
  },
  {
    name: "Runway Gen-4.5",
    by: "Runway ML",
    color: "#FF5E7D",
    tags: ["#1 Cinema", "4K", "15s"],
    quality: 93,
    speed: 88,
    realism: 89,
    res: "4K · 15s",
    badge: "",
  },
  {
    name: "Luma Ray3",
    by: "Luma AI",
    color: "#9D7AFF",
    tags: ["HDR Physics", "4K", "10s"],
    quality: 90,
    speed: 90,
    realism: 91,
    res: "4K · 10s",
    badge: "",
  },
  {
    name: "Pika 2.2",
    by: "Pika Labs",
    color: "#FFB930",
    tags: ["Fast", "1080p", "8s"],
    quality: 84,
    speed: 95,
    realism: 82,
    res: "1080p · 8s",
    badge: "FAST",
  },
];

export const MODEL_CREDITS: Record<string, number> = {
  "Kling 2.6": 42,
  "Veo 3.1": 55,
  "Sora 2 Pro": 60,
  "Runway Gen-4.5": 38,
  "Luma Ray3": 30,
  "Pika 2.2": 20,
};

export const MODEL_COLOR: Record<string, string> = {
  "Kling 2.6": "#3EE8FF",
  "Veo 3.1": "#4285F4",
  "Sora 2 Pro": "#10A37F",
  "Runway Gen-4.5": "#FF5E7D",
  "Luma Ray3": "#9D7AFF",
  "Pika 2.2": "#FFB930",
};

export const NAV: NavGroup[] = [
  {
    group: "Studio",
    items: [
      { id: "dashboard", label: "Dashboard", badge: null, badgeCls: "" },
      { id: "generate", label: "Generate", badge: "AI", badgeCls: "nb-g" },
      { id: "videos", label: "My Videos", badge: "8", badgeCls: "nb-n" },
      { id: "storyboard", label: "Storyboard", badge: null, badgeCls: "" },
      { id: "prompts", label: "Prompt Library", badge: "3", badgeCls: "nb-r" },
    ],
  },
  {
    group: "AI Models",
    items: [
      { id: "models", label: "Model Library", badge: "7", badgeCls: "nb-g" },
      { id: "benchmarks", label: "Benchmarks", badge: null, badgeCls: "" },
      { id: "api", label: "API & Plugins", badge: null, badgeCls: "" },
    ],
  },
  {
    group: "Account",
    items: [
      { id: "team", label: "Team", badge: null, badgeCls: "" },
      { id: "settings", label: "Settings", badge: null, badgeCls: "" },
    ],
  },
];

export const PAGE_TITLES: PageTitles = {
  dashboard: "Dashboard",
  generate: "Generate Video",
  videos: "My Videos",
  storyboard: "Storyboard",
  prompts: "Prompt Library",
  models: "Model Library",
  benchmarks: "Benchmarks",
  api: "API & Plugins",
  team: "Team",
  settings: "Settings",
};

export const STUB_PAGES: string[] = ["prompts", "benchmarks", "api", "team"];
